[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ripcord_vault = "84h2juN2WaFhZtGbaqmeWVVe7HQCUXnDRRtbGZQeAeTu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test tests/vault.test.ts"
