[package]
name = "ripcord-backtest"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ripcord-policy = { path = "../ripcord-policy" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
ureq = { workspace = true }
bs58 = { workspace = true }
chrono = { workspace = true }
